/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package interfaz;

import datos.Aeropuerto;
import datos.VueloBase;
import datos.VueloDiario;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import logica.LogicaNegocio;

/**
 *
 * @author jrubioa
 */
public class DlgVuelosDiarios extends javax.swing.JDialog {

    private VueloDiario vueloDiario;
    private Aeropuerto aeropuerto;
    
    
    private boolean change = false;
    private boolean isvalid = false;
    
    SimpleDateFormat sdH = new SimpleDateFormat("HH:mm");
    SimpleDateFormat sdF = new SimpleDateFormat("dd/MM/yyyy");

    public boolean isChange() {
        return change;
    }
    
    public VueloDiario getVueloDiario() {
        return vueloDiario;
    }

    public void setVueloDiario(VueloDiario vueloDiario) {
        this.vueloDiario = vueloDiario;
    }
    /**
     * Creates new form DlgVuelosDiarios
     */
    public DlgVuelosDiarios(java.awt.Frame parent, boolean modal, VueloDiario vueloDiario) {
        super(parent, modal);
        initComponents();
        btnGuardar.setEnabled(false);
        
        this.vueloDiario = vueloDiario;
        
        LogicaNegocio.getAllAeropuertos().forEach(m->this.cbCodigoVueloBase.addItem(m));
        this.txtFechaVuelo.setText(sdF.format(this.vueloDiario.getFechaVuelo()));
        this.txtHoraSalidaReal.setText(sdH.format(this.vueloDiario.getHoraSalidaReal()));
        this.txtHoraLegadaReal.setText(sdH.format(this.vueloDiario.getHoraLegadaReal()));
        this.txtNumeroPlazas.setText(String.valueOf(this.vueloDiario.getNumeroPlazas()));
        this.txtPrecio.setText(String.valueOf(this.vueloDiario.getPrecio()));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGuardar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtFechaVuelo = new javax.swing.JTextField();
        txtHoraLegadaReal = new javax.swing.JTextField();
        txtHoraSalidaReal = new javax.swing.JTextField();
        txtNumeroPlazas = new javax.swing.JTextField();
        txtPrecio = new javax.swing.JTextField();
        cbCodigoVueloBase = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnSalir.setText("Cancelar/salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        jLabel1.setText("Codigo Vuelo Base");

        jLabel2.setText("fecha Vuelo");

        jLabel3.setText("Hora Salida Real");

        jLabel4.setText("Hora Llegada Real");

        jLabel5.setText("Numero Plazas");

        jLabel6.setText("Precio");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(btnGuardar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtFechaVuelo)
                    .addComponent(txtNumeroPlazas, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                    .addComponent(txtPrecio, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                    .addComponent(txtHoraLegadaReal, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                    .addComponent(txtHoraSalidaReal, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                    .addComponent(btnSalir, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cbCodigoVueloBase, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(97, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cbCodigoVueloBase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtFechaVuelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtHoraSalidaReal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtHoraLegadaReal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtNumeroPlazas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(btnSalir))
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed

        this.validate();
        this.isvalid=true;
        if(isvalid){
            try {
                this.change = true;

                if (this.vueloDiario == null){
                    this.vueloDiario = new VueloDiario();
                }
                
                VueloDiario m = (VueloDiario)cbCodigoVueloBase.getSelectedItem();
                this.vueloDiario.setCodigoVueloBase(m.getCodigoVueloBase());

                this.vueloDiario.setFechaVuelo(sdF.parse(txtFechaVuelo.getText()));
                this.vueloDiario.setHoraSalidaReal(sdH.parse(txtHoraSalidaReal.getText()));
                this.vueloDiario.setHoraLegadaReal(sdH.parse(txtHoraLegadaReal.getText()));
                this.vueloDiario.setNumeroPlazas(Integer.parseInt(txtNumeroPlazas.getText()));
                this.vueloDiario.setPrecio(Float.parseFloat(txtPrecio.getText()));

                
            } catch (ParseException ex) {
                Logger.getLogger(DlgVuelosDiarios.class.getName()).log(Level.SEVERE, null, ex);
            }

        }else{
            this.change = false;
        }

        this.setVisible(false);
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.setVisible(false);
        this.change = false;
    }//GEN-LAST:event_btnSalirActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<Aeropuerto> cbCodigoVueloBase;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txtFechaVuelo;
    private javax.swing.JTextField txtHoraLegadaReal;
    private javax.swing.JTextField txtHoraSalidaReal;
    private javax.swing.JTextField txtNumeroPlazas;
    private javax.swing.JTextField txtPrecio;
    // End of variables declaration//GEN-END:variables

    
    // Metodo que se usa para desabilitar o habilitar controles
    private void setControlState(boolean state) {
        this.cbCodigoVueloBase.setEditable(state);
        this.txtFechaVuelo.setEditable(state);
        this.txtHoraSalidaReal.setEditable(state);
        this.txtHoraLegadaReal.setEditable(state);
        this.txtNumeroPlazas.setEditable(state);
        this.txtPrecio.setEditable(state);
        
    }
    
public void validate(){
        super.validate();
    }

}
