/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package interfaz;

import datos.Aeropuerto;
import datos.VueloBase;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import logica.LogicaNegocio;

/**
 *
 * @author jrubioa
 */
public class DlgVuelosBase extends javax.swing.JDialog {

    
    private VueloBase vueloBase;
    private Aeropuerto aeropuerto;
    
    String pulIataOrigen;
    String pulIataDestino;
            
    private boolean change = false;
    private boolean isvalid = false;
    
    SimpleDateFormat sd = new SimpleDateFormat("HH:mm");

    public boolean isChange() {
        return change;
    }
    
    public VueloBase getVueloBase() {
        return vueloBase;
    }

    public void setVueloBase(VueloBase vueloBase) {
        this.vueloBase = vueloBase;
    }
    /**
     * Creates new form DlgVuelosBase
     */
    public DlgVuelosBase(java.awt.Frame parent, boolean modal, VueloBase vueloBase) {
        super(parent, modal);
        initComponents();
        //btnGuardar.setEnabled(false);
        
        this.vueloBase = vueloBase;
        this.txtCodigoVuelo.setText(this.vueloBase.getCodigoVuelo());
        //this.cbCodigoIataOrigen.setText(this.vueloBase.getAeropuertoOrigen());
        //this.cbCodigoIataDestino.setText(this.vueloBase.getAeropuertoDestino());
        this.txtNumerPlazas.setText(String.valueOf(this.vueloBase.getNumeroPlazas()));
        this.txtHoraSalida.setText(sd.format(this.vueloBase.getHoraSalida()));
        this.txtHoraLlegada.setText(sd.format(this.vueloBase.getHoraLlegada()));
        
        this.txtDiasSemanaVuelo.setText(this.vueloBase.getDiasSemanaVuelo());
        
        LogicaNegocio.getAllAeropuertos().forEach(m->this.cbCodigoIataDestino.addItem(m));
        LogicaNegocio.getAllAeropuertos().forEach(m->this.cbCodigoIataOrigen.addItem(m));
        
        cbCodigoIataDestino.setSelectedItem(LogicaNegocio.getAeropuertoByCodigoIATA(this.vueloBase.getCodigoIATADestino()));
        
        pulIataOrigen = cbCodigoIataOrigen.getSelectedItem().toString();
        pulIataDestino = cbCodigoIataDestino.getSelectedItem().toString();
        
        
        //if(pulIataOrigen == "OVD\\ W" || pulIataDestino == "\\ WOVD"){
            //txtError.setText("");
            btnGuardar.setEnabled(true);
            //txtError.setText("Nota: Recuerde que su Base es OVD, solo se puede gestionar vuelos con este codigo. Gracias");
            //txtError.setEnabled(false);
        //}else{
            //btnGuardar.setEnabled(false);
            //txtError.setText("Nota: Por favor, no puede gestionar vuelos fuera de su Base OVD, seleciona OVD. Gracias");
            txtError.setEnabled(false);
        //}
        
    }
    
    public static String getHoraFecha(Date fecha) {
        SimpleDateFormat sdf = new SimpleDateFormat("HH:mm");
        return sdf.format(fecha);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGuardar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtCodigoVuelo = new javax.swing.JTextField();
        txtNumerPlazas = new javax.swing.JTextField();
        txtHoraSalida = new javax.swing.JTextField();
        txtHoraLlegada = new javax.swing.JTextField();
        txtDiasSemanaVuelo = new javax.swing.JTextField();
        cbCodigoIataOrigen = new javax.swing.JComboBox<>();
        cbCodigoIataDestino = new javax.swing.JComboBox<>();
        txtError = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gestion De Vuelos Base");

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnSalir.setText("Cancelar/salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        jLabel1.setText("Codigo del Vuelo");

        jLabel2.setText("Codigo IATA Origen");

        jLabel3.setText("Codigo IATA Destino");

        jLabel4.setText("Numero de Plazas");

        jLabel5.setText("Hora de Salida");

        jLabel6.setText("Dias de la semana de Vuelo");

        jLabel7.setText("Hora de Llegada");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(btnGuardar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSalir)
                .addGap(134, 134, 134))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtDiasSemanaVuelo, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                            .addComponent(txtHoraLlegada, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                            .addComponent(txtHoraSalida, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                            .addComponent(txtNumerPlazas, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                            .addComponent(txtCodigoVuelo)
                            .addComponent(cbCodigoIataDestino, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbCodigoIataOrigen, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(txtError, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCodigoVuelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbCodigoIataOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbCodigoIataDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtNumerPlazas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtHoraSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtHoraLlegada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtDiasSemanaVuelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(btnSalir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtError, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed

        this.validate();
        pulIataOrigen = cbCodigoIataOrigen.getSelectedItem().toString();
        pulIataDestino = cbCodigoIataDestino.getSelectedItem().toString();
        System.out.println("Prueba javi " +pulIataOrigen );
        System.out.println("Prueba javi " +pulIataDestino );
        
        this.isvalid=true;
        if(isvalid &&(pulIataOrigen.equals("OVD") || pulIataDestino.equals("OVD") )){
            try {
                this.change = true;

                if (this.vueloBase == null){
                    this.vueloBase = new VueloBase();
                }
                this.vueloBase.setCodigoVuelo(txtCodigoVuelo.getText());

                Aeropuerto o = (Aeropuerto)cbCodigoIataOrigen.getSelectedItem();
                this.vueloBase.setCodigoIATAOrigen(o.getCodigoIATA());
                Aeropuerto d = (Aeropuerto)cbCodigoIataDestino.getSelectedItem();
                this.vueloBase.setCodigoIATAOrigen(d.getCodigoIATA());
                
                this.vueloBase.setNumeroPlazas(Integer.parseInt(txtNumerPlazas.getText()));
                this.vueloBase.setHoraSalida(sd.parse(txtHoraSalida.getText()));
                this.vueloBase.setHoraLlegada(sd.parse(txtHoraLlegada.getText()));
                this.vueloBase.setDiasSemanaVuelo(txtDiasSemanaVuelo.getText());
                this.setVisible(false);
            } catch (ParseException ex) {
                Logger.getLogger(DlgVuelosBase.class.getName()).log(Level.SEVERE, null, ex);
            }


        }else{
            this.change = false;
            txtError.setText("Nota: Por favor, no puede gestionar vuelos fuera de su Base OVD, seleciona OVD. Gracias");
            txtError.setEnabled(false);
        }

        //this.setVisible(false);
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.setVisible(false);
        this.change = false;
    }//GEN-LAST:event_btnSalirActionPerformed




    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<Aeropuerto> cbCodigoIataDestino;
    private javax.swing.JComboBox<Aeropuerto> cbCodigoIataOrigen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txtCodigoVuelo;
    private javax.swing.JTextField txtDiasSemanaVuelo;
    private javax.swing.JLabel txtError;
    private javax.swing.JTextField txtHoraLlegada;
    private javax.swing.JTextField txtHoraSalida;
    private javax.swing.JTextField txtNumerPlazas;
    // End of variables declaration//GEN-END:variables

public void setControlState(boolean enabled) {
        this.txtCodigoVuelo.setEnabled(enabled);
        //this.cbCodigoIataDestino.setEnabled(enabled);
        //this.cbCodigoIataOrigen.setEnabled(enabled);
        this.txtNumerPlazas.setEnabled(enabled);
        this.txtHoraSalida.setEnabled(enabled);
        this.txtHoraLlegada.setEnabled(enabled);
        this.txtDiasSemanaVuelo.setEnabled(enabled);
    }

    @Override
    public void validate() {
        super.validate();
    }
}