/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaz;

import datos.Company;
import javax.swing.JOptionPane;
import logica.CompanyModelTable;
import logica.LogicaNegocio;

/**
 * Formulario donde se muestran los datos de las comapañias del sistema
 * @author jrubioa
 */
public class FrmCompany extends javax.swing.JFrame {

    // Se utiliza el patron Singleton, con el fin de que se actualice siempre la misma ventana
    //Por tanto se decalara lo siguiente
    // De esta manera si ya esta instanciada, devuelve la misma y en caso de que no este instalaciada (caso null), crearia una nueva
    
    private static FrmCompany INSTANCE = null;
    
    public static FrmCompany getInstance() {
        if (INSTANCE == null) { 
            INSTANCE = new FrmCompany();
        }
        return INSTANCE;
    }
    
    /**
     * Creates new form FrmCompany
     */
    public FrmCompany() {
        initComponents();
        fillTableCompany();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblCompany = new javax.swing.JTable();
        btnEditar = new javax.swing.JButton();
        btnAnadir = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        txtError = new javax.swing.JTextField();

        setTitle("Compañias del Aeropuerto");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        tblCompany.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblCompany);

        btnEditar.setText("Editar o Consultar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnAnadir.setText("Añadir");
        btnAnadir.setToolTipText("");
        btnAnadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnadirActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnEditar)
                        .addGap(39, 39, 39)
                        .addComponent(btnAnadir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEliminar))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtError, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(104, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEditar)
                    .addComponent(btnAnadir)
                    .addComponent(btnEliminar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtError, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * 
     * Evento que permite eliminar un registro del sistema
     */
    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        //Nos da dal compañia de la fila selecionada
        Company comp_select = LogicaNegocio.getAllCompany().get(tblCompany.getSelectedRow());
        int respuesta_borrado =JOptionPane.showConfirmDialog(this, "¿Desea borrar la fila seleciona? "+comp_select.getCodigo(), 
                "Borrado de compañia ", JOptionPane.YES_NO_OPTION);
        if(respuesta_borrado ==JOptionPane.OK_OPTION){
            LogicaNegocio.deleteCompany(comp_select.getPrefijo());
        }
        //con el fin de que refrescar la tabla
        fillTableCompany();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnAnadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnadirActionPerformed
        Company comp_select = new Company();
        comp_select.setPrefijo(0);
        comp_select.setCodigo("");
        comp_select.setDireccion("");
        comp_select.setNombre("");
        comp_select.setTelefonoAeropuerto("");
        comp_select.setTelefonoPasajero("");
        comp_select.setcodigoMunicipio("");
        
        
        DlgDatosCompany dlgDatosCompany = new DlgDatosCompany(this, true, comp_select);
        //dlgDatosCompany.setCompany(comp_select);
        dlgDatosCompany.setVisible(true);
        // Solamente si se ha cambiado se actualiza y se añade la compañia
        if (dlgDatosCompany.isChange()){
            txtError.setText("");
            txtError.setEnabled(false);
            // Se añade la nueva compañia
            LogicaNegocio.addCompany(dlgDatosCompany.getCompany());
            // Se actualiza la tabla de la interface
            this.fillTableCompany();
        }else{
            txtError.setEnabled(true);
            txtError.setText("Inserta una compañia correcta. Ya existe un Prefijo o un codigo con valor. Gracias");
        }
        
    }//GEN-LAST:event_btnAnadirActionPerformed

    /**
     * 
     * Evento que permite editar un registro del sistema
     */
    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        
        //Nos da dal compañia de la fila selecionada
       Company comp_select = LogicaNegocio.getAllCompany().get(tblCompany.getSelectedRow());
       
       DlgDatosCompany dlgDatosCompany = new DlgDatosCompany(this, true, comp_select);
       dlgDatosCompany.setCompany(comp_select);
       dlgDatosCompany.setVisible(true);
        
       if (dlgDatosCompany.isChange()){
            LogicaNegocio.updateCompany(comp_select, dlgDatosCompany.getCompany());
            fillTableCompany();
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    /**
     * 
     * Evento que permite guardar los cambios en el .csv 
     */
    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        LogicaNegocio.escribirCompany(LogicaNegocio.getAllCompany());
    }//GEN-LAST:event_formWindowClosing



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnadir;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblCompany;
    private javax.swing.JTextField txtError;
    // End of variables declaration//GEN-END:variables

    /**
     * Metodo que permite tener actualizada la tabla con los datos del sistema
     */
    private void fillTableCompany() {
        tblCompany.setModel(new CompanyModelTable(LogicaNegocio.getAllCompany()));
        
    }
}
