/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaz;

import datos.Company;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.logging.Logger;
import logica.CompanyModelTable;
import logica.CompanyVuelosModelTable;
import logica.LogicaNegocio;

/**
 * Formulario donde se muestran los datos en el panel de compañias
 * @author jrubioa
 */
public class FrmPanelCompany extends javax.swing.JFrame {

    SimpleDateFormat sdH = new SimpleDateFormat ("dd/MM/yyyy");
    /**
     * Creates new form FrmPanelCompany
     */
    public FrmPanelCompany() {
        initComponents();
        
        //fillTableCompany1();
        
        List<Company> lstCompany = LogicaNegocio.getAllCompany();
                for (int j = 0; j < lstCompany.size(); j++) {
            String nombre_Comp = lstCompany.get(j).getNombre();
            cbCompany.addItem(nombre_Comp);
        }
        
        Date fecha_Actual = new Date();
        txtFecha.setText(sdH.format(fecha_Actual));
        
        fillTableCompany1();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtFecha = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPanelCompany = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        cbCompany = new javax.swing.JComboBox<>();
        txtError = new javax.swing.JTextField();

        setTitle("Panel de Compañias");

        jLabel1.setText("Inserta la fecha (Ej: 01/01/2024):");

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        tblPanelCompany.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblPanelCompany);

        jLabel2.setText("Company");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtError)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtFecha, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cbCompany, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(29, 29, 29)
                        .addComponent(btnBuscar)))
                .addGap(68, 68, 68))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(cbCompany, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(btnBuscar)))
                .addGap(18, 18, 18)
                .addComponent(txtError, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
    * 
    * Evento que buscar en el sistema
    */
    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        fillTableCompany1();
    }//GEN-LAST:event_btnBuscarActionPerformed

    /**
     * Metodo que permite tener actualizada la tabla con los datos del sistema
     */
    public void fillTableCompany1() {              
        try {
            Date fecha_Buscar = sdH.parse(txtFecha.getText());
            Company company_Buscar = LogicaNegocio.getCompanyaByNombre(cbCompany.getSelectedItem().toString());
            tblPanelCompany.setModel(new CompanyVuelosModelTable(LogicaNegocio.getVuelosCompany(fecha_Buscar,company_Buscar))); 
            if(LogicaNegocio.getVuelosCompany(fecha_Buscar,company_Buscar).isEmpty()){
                txtError.setText("No existe ningún vuelo");
                txtError.setEnabled(true);
            }else{
                txtError.setText("");
                txtError.setEnabled(false);
            }
            
        } catch (ParseException ex) {
            Logger.getLogger("Fallo");
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JComboBox<String> cbCompany;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPanelCompany;
    private javax.swing.JTextField txtError;
    private javax.swing.JTextField txtFecha;
    // End of variables declaration//GEN-END:variables

    /**
     * Metodo que permite tener actualizada la tabla con los datos del sistema
     */
    private void fillTableCompany() {
        tblPanelCompany.setModel(new CompanyModelTable(LogicaNegocio.getAllCompany()));
        
    }
}
