/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaz;


import datos.VueloDiario;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Logger;
import logica.LogicaNegocio;
import logica.VuelosDiariosModelTable;

/**
 * Formulario donde se muestran los datos del panel de Llegadas del sistema
 * @author jrubioa
 */
public class FrmPanelLlegadas extends javax.swing.JFrame {
    
    SimpleDateFormat sdH = new SimpleDateFormat ("dd/MM/yyyy");

    /**
     * Creates new form FrmPanelLlegadas
     */
    public FrmPanelLlegadas() {
        initComponents();
        
        Date fecha_Actual = new Date();
        txtFecha.setText(sdH.format(fecha_Actual));
        fillTableVuelosDiarios1();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblPanelLlegadas = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtFecha = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        txtError = new javax.swing.JTextField();

        setTitle("Panel de Llegadas");

        tblPanelLlegadas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblPanelLlegadas);

        jLabel1.setText("Inserta la fecha (Ej: 01/01/2024):");

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtFecha, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(btnBuscar))
                    .addComponent(txtError, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(92, 92, 92))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtError, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * 
     * Evento que permite buscar en el sistema
     */
    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
            fillTableVuelosDiarios1();

    }//GEN-LAST:event_btnBuscarActionPerformed

    /**
     * Lista con las llegadas del sistema
     */
    private static List<VueloDiario> lstPanelSalida = new ArrayList<>();
    
    /**
     * Se obtiene los vuelos diarios dado su fecha
     * @param fecha_Buscar fecha a buscar
     * @return devuelve el vuelo diario a partir de la fecha
     */
    public static List<VueloDiario> getSalidasByDate(Date fecha_Buscar) {
    lstPanelSalida.clear();
    for (VueloDiario vuelo : LogicaNegocio.getAllVueloDiario()) {
        if ((vuelo.getFechaVuelo().equals(fecha_Buscar))) {
             lstPanelSalida.add(vuelo);
        }
    }
        return lstPanelSalida;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPanelLlegadas;
    private javax.swing.JTextField txtError;
    private javax.swing.JTextField txtFecha;
    // End of variables declaration//GEN-END:variables

    /**
     * Metodo que permite tener actualizada la tabla con los datos del sistema
     */
    private void fillTableVuelosDiarios1() {
        try {
            txtError.setText("");
            txtError.setEnabled(true);
            Date fecha_Buscar = sdH.parse(txtFecha.getText());
            tblPanelLlegadas.setModel(new VuelosDiariosModelTable(getSalidasByDate(fecha_Buscar)));
            if(getSalidasByDate(fecha_Buscar).isEmpty()){
                txtError.setText("No hay vuelos para esa fecha. Intentelo con otra fecha. Gracias");
            }else{
                txtError.setText("");
                txtError.setEnabled(false);
            }
        } catch (ParseException ex) {
            Logger.getLogger("Por favor, inserta una fecha");
            txtError.setText("Por favor, inserta una fecha");
        }
        
    }
    
    /**
     * Metodo que permite tener actualizada la tabla con los datos del sistema
     */
    private void fillTableVuelosDiarios() {
        tblPanelLlegadas.setModel(new VuelosDiariosModelTable(LogicaNegocio.getAllVueloDiario()));
        
    }

}
