/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaz;

import datos.VueloDiario;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Logger;
import logica.LogicaNegocio;
import logica.VuelosDiariosModelTable;

/**
 *
 * @author usuario
 */
public class FrmPanelSalida extends javax.swing.JFrame {

    SimpleDateFormat sdH = new SimpleDateFormat ("dd/MM/yyyy");
    /**
     * Creates new form FrmPanelSalida
     */
    public FrmPanelSalida() {
        initComponents();
        //fillTableVuelosDiarios();
        
        Date fecha_Actual = new Date();
        txtFecha.setText(sdH.format(fecha_Actual));
        fillTableVuelosDiarios1();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblPanelSalidas = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtFecha = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();

        setTitle("Panel de Salidas");

        tblPanelSalidas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblPanelSalidas);

        jLabel1.setText("Inserta la fecha (Ej: 01/01/2024):");

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFecha, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(btnBuscar)))
                .addGap(55, 55, 55))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar))
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        fillTableVuelosDiarios1();
       
        
    }//GEN-LAST:event_btnBuscarActionPerformed

private static List<VueloDiario> lstPanelSalida = new ArrayList<>();
    
public static List<VueloDiario> getSalidasByDate(Date fecha_Buscar) {
    lstPanelSalida.clear();
    for (VueloDiario vuelo : LogicaNegocio.getAllVueloDiario()) {
        if ((vuelo.getFechaVuelo().equals(fecha_Buscar))) {
             lstPanelSalida.add(vuelo);
        }
    }
        return lstPanelSalida;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPanelSalidas;
    private javax.swing.JTextField txtFecha;
    // End of variables declaration//GEN-END:variables


    private void fillTableVuelosDiarios1() {
        try {
            Date fecha_Buscar = sdH.parse(txtFecha.getText());
            tblPanelSalidas.setModel(new VuelosDiariosModelTable(getSalidasByDate(fecha_Buscar)));
            
        } catch (ParseException ex) {
            Logger.getLogger("Por favor, inserta una fecha");
        }
        
    }
    
    private void fillTableVuelosDiarios() {
        tblPanelSalidas.setModel(new VuelosDiariosModelTable(LogicaNegocio.getAllVueloDiario()));
        
    }

}
