/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaz;

import datos.VueloBase;
import java.awt.Dimension;
import javafx.application.Platform;
import javafx.embed.swing.JFXPanel;
import javafx.scene.Scene;
import javafx.scene.web.WebEngine;
import javafx.scene.web.WebView;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import logica.LogicaNegocio;
import logica.VuelosBaseModelTable;

/**
 *
 * @author usuario
 */
public class FrmVuelosBase extends javax.swing.JFrame {

    // Se utiliza el patron Singleton, con el fin de que se actualice siempre la misma ventana
    //Por tanto se decalara lo siguiente
    // De esta manera si ya esta instanciada, devuelve la misma y en caso de que no este instalaciada (caso null), crearia una nueva
    
    private static FrmVuelosBase INSTANCE = null;
    
    private JFXPanel jfxPanel; 
    private JFrame frame;
    
    public static FrmVuelosBase getInstance() {
        if (INSTANCE == null) { 
            INSTANCE = new FrmVuelosBase();
        }
        return INSTANCE;
    }
    
    /**
     * Creates new form FrmVuelosBase
     */
    public FrmVuelosBase() {
        initComponents();
        setHelp();
        fillTableVuelosBase();
    }
    private void setHelp() { 
        jfxPanel = new JFXPanel(); 
        frame = new JFrame("Ayuda"); 
        frame.setSize(new Dimension(500, 500)); 
        frame.add(jfxPanel); 
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnEditar = new javax.swing.JButton();
        btnAnadir = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblVuelosBase = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        mmuAyudaMain = new javax.swing.JMenu();
        mmuAyuda = new javax.swing.JMenuItem();

        setTitle("Gestion de Vuelos Base");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        btnEditar.setText("Editar o Consultar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnAnadir.setText("Añadir");
        btnAnadir.setToolTipText("");
        btnAnadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnadirActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        tblVuelosBase.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblVuelosBase);

        mmuAyudaMain.setText("Ayuda");

        mmuAyuda.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        mmuAyuda.setText("Ayuda principal");
        mmuAyuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mmuAyudaActionPerformed(evt);
            }
        });
        mmuAyudaMain.add(mmuAyuda);

        jMenuBar1.add(mmuAyudaMain);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnEditar)
                        .addGap(53, 53, 53)
                        .addComponent(btnAnadir)
                        .addGap(54, 54, 54)
                        .addComponent(btnEliminar)))
                .addContainerGap(140, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEditar)
                    .addComponent(btnAnadir)
                    .addComponent(btnEliminar))
                .addGap(38, 38, 38))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed

        //Nos da dal compañia de la fila selecionada
        VueloBase comp_select = LogicaNegocio.getAllVueloBase().get(tblVuelosBase.getSelectedRow());

        DlgVuelosBase dlgDatosVuelosBase = new DlgVuelosBase(this, true, comp_select);
        dlgDatosVuelosBase.setVueloBase(comp_select);
        dlgDatosVuelosBase.setVisible(true);

        if (dlgDatosVuelosBase.isChange()){
            LogicaNegocio.updateVueloBase(comp_select, dlgDatosVuelosBase.getVueloBase());
            fillTableVuelosBase();
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnAnadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnadirActionPerformed
        DlgVuelosBase dlgDatosVuelosBase = new DlgVuelosBase(this, true, null);
        dlgDatosVuelosBase.setVisible(true);
        // Solamente si se ha cambiado se actualiza y se añade la compañia
        if (dlgDatosVuelosBase.isChange()){
            // Se añade la nueva compañia
            LogicaNegocio.addVueloBase(dlgDatosVuelosBase.getVueloBase());
            // Se actualiza la tabla de la interface
            this.fillTableVuelosBase();
        }

    }//GEN-LAST:event_btnAnadirActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        //Nos da dal compañia de la fila selecionada
        VueloBase comp_select = LogicaNegocio.getAllVueloBase().get(tblVuelosBase.getSelectedRow());
        int respuesta_borrado =JOptionPane.showConfirmDialog(this, "¿Desea borrar la fila seleciona? "+comp_select.getCodigoVuelo(),
            "Borrado de compañia ", JOptionPane.YES_NO_OPTION);
        if(respuesta_borrado ==JOptionPane.OK_OPTION){
            LogicaNegocio.deleteVueloBase(comp_select.getCodigoVuelo());
        }
        //con el fin de que refrescar la tabla
        fillTableVuelosBase();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        LogicaNegocio.escribirVueloBase(LogicaNegocio.getAllVueloBase());
    }//GEN-LAST:event_formWindowClosing

    private void mmuAyudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mmuAyudaActionPerformed
        //Se llama al metodo de abajo con la URL a mostrar
        openWebView("https://es.wikipedia.org/wiki/Anexo:Aeropuertos_seg%C3%BAn_el_c%C3%B3digo_IATA");
    }//GEN-LAST:event_mmuAyudaActionPerformed

// Basicamente esto es para que carge la pagina URL
    private void openWebView(String url) { 
            Platform.runLater(() -> { 
            WebView webView = new WebView(); 
            WebEngine webEngine = webView.getEngine(); 
            webEngine.load(url); 
            jfxPanel.setScene(new Scene(webView)); 
            frame.setVisible(true); 
        }); 
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnadir;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem mmuAyuda;
    private javax.swing.JMenu mmuAyudaMain;
    private javax.swing.JTable tblVuelosBase;
    // End of variables declaration//GEN-END:variables
 
    private void fillTableVuelosBase() {
        tblVuelosBase.setModel(new VuelosBaseModelTable(LogicaNegocio.getAllVueloBase()));
        
    }

}
